flags: {}
packages:
- chart/
- chart-cairo/
- chart-diagrams/
- chart-tests/
- chart-gtk/
extra-deps:
- gtk-0.14.6
flags:
  gtk:
    # This needs to be true on osx
    have-quartz-gtk: false
resolver: lts-8.5
nix:
  packages: [pkgconfig, cairo, zlib, pango, gtk2]