flags: {}
packages:
- chart/
- chart-cairo/
- chart-diagrams/
- chart-tests/
- chart-gtk/
- chart-gtk3/
#flags:
#  gtk:
#    # This needs to be true on osx
#    have-quartz-gtk: false
resolver: lts-19.25
extra-deps:
- cairo-0.13.8.2
- diagrams-cairo-1.4.2
- diagrams-postscript-1.5.1
- gtk-0.15.7
- gtk3-0.15.7
- gio-0.13.8.2
- glib-0.13.8.2
- pango-0.13.8.2
- statestack-0.3.1
nix:
  packages: [pkgconfig, cairo, zlib, pango, xorg.xproto, xorg.libX11, gtk2, gtk3]
